package Login;

import conexionSQL.conexionMysql;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class accesoBusqueda extends javax.swing.JFrame {

    conexionMysql cc = new conexionMysql();
    Connection con = cc.conexion();
    
    public accesoBusqueda() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaPatenteBusqueda = new javax.swing.JLabel();
        etiquetaRUNnoAction = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiquetaRUNBuscar = new javax.swing.JLabel();
        etiquetaEstBuscar = new javax.swing.JLabel();
        txtPatenteBusqueda = new javax.swing.JTextField();
        aceptarBusqueda = new javax.swing.JButton();
        etiquetaNombreBuscar = new javax.swing.JLabel();
        etiquetaApellidoBuscar = new javax.swing.JLabel();
        etiquetaBlockBuscar = new javax.swing.JLabel();
        etiquetaDepartamentoBuscar = new javax.swing.JLabel();
        etiquetaTelefonoBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar y Autorizar - Modo Manual");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaPatenteBusqueda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaPatenteBusqueda.setText("Patente:");
        jPanel1.add(etiquetaPatenteBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        etiquetaRUNnoAction.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etiquetaRUNnoAction.setText("RUN:");
        jPanel1.add(etiquetaRUNnoAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Block:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Télefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Estacionamiento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        etiquetaRUNBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaRUNBuscar.setText(" ");
        jPanel1.add(etiquetaRUNBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, -1));

        etiquetaEstBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaEstBuscar.setText(" ");
        jPanel1.add(etiquetaEstBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 60, -1));

        txtPatenteBusqueda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPatenteBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatenteBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPatenteBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, -1));

        aceptarBusqueda.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        aceptarBusqueda.setText("Aceptar");
        aceptarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        etiquetaNombreBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaNombreBuscar.setText(" ");
        jPanel1.add(etiquetaNombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, -1));

        etiquetaApellidoBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaApellidoBuscar.setText(" ");
        jPanel1.add(etiquetaApellidoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, -1));

        etiquetaBlockBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaBlockBuscar.setText(" ");
        jPanel1.add(etiquetaBlockBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, -1));

        etiquetaDepartamentoBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaDepartamentoBuscar.setText(" ");
        jPanel1.add(etiquetaDepartamentoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, -1));

        etiquetaTelefonoBuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaTelefonoBuscar.setText(" ");
        jPanel1.add(etiquetaTelefonoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatenteBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatenteBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteBusquedaActionPerformed

    private void aceptarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBusquedaActionPerformed
        try{
            String patente = txtPatenteBusqueda.getText();
            
            if (patente.length()>0){
                String sql = "SELECT * FROM propietarios WHERE patente = '" + patente + "' ";
                
                Statement s = con.prepareStatement(sql);
                ResultSet rs = s.executeQuery(sql);
                
                if (rs.next()){
                    String run = rs.getString(3);
                    String nombre = rs.getString(4);
                    String apellido = rs.getString(5);
                    String block = rs.getString(6);
                    String departamento = rs.getString(7);
                    String estacionamiento = rs.getString(8);
                    String telefono = rs.getString(9);
                    
                    etiquetaRUNBuscar.setText(run);
                    etiquetaNombreBuscar.setText(nombre);
                    etiquetaApellidoBuscar.setText(apellido);
                    etiquetaBlockBuscar.setText(block);
                    etiquetaDepartamentoBuscar.setText(departamento);
                    etiquetaEstBuscar.setText(estacionamiento);
                    etiquetaTelefonoBuscar.setText(telefono);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Patente no registrada en el sistema.");
                    
                    txtPatenteBusqueda.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Seleccione Patente");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexión " + ex);
        }
    }//GEN-LAST:event_aceptarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accesoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accesoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accesoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accesoBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accesoBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBusqueda;
    private javax.swing.JLabel etiquetaApellidoBuscar;
    private javax.swing.JLabel etiquetaBlockBuscar;
    private javax.swing.JLabel etiquetaDepartamentoBuscar;
    private javax.swing.JLabel etiquetaEstBuscar;
    private javax.swing.JLabel etiquetaNombreBuscar;
    private javax.swing.JLabel etiquetaPatenteBusqueda;
    private javax.swing.JLabel etiquetaRUNBuscar;
    private javax.swing.JLabel etiquetaRUNnoAction;
    private javax.swing.JLabel etiquetaTelefonoBuscar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtPatenteBusqueda;
    // End of variables declaration//GEN-END:variables
}
